### ISSUE TITLE
_gtk_style_provider_private_get_settings assertion failed

### ISSUE THREAD

**Issue by faultydev** [sezanzeb/key-mapper#28] opened 2021-01-30 15:36 UTC
I started the service and did the stuff with sudo (doas)..
It aint working...

I've attached details

---

Arch Linux x86_64 
5.10.11-arch1-1 
GNOME 3.38.3

---

No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
Loaded config from "/home/faulty/.config/key-mapper/config.json"
0.78284 DEBUG: logger.py, line 181, Using rich.traceback
0.81042 INFO: logger.py, line 152, key-mapper 0.6.0
0.81116 INFO: logger.py, line 155, python-evdev 1.4.0
0.81126 WARNING: logger.py, line 161, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.81139 DEBUG: logger.py, line 167, pid 28879
0.85933 DEBUG: data.py, line 85, Found data at "/usr/share/key-mapper"

(key-mapper-gtk:28879): Gtk-CRITICAL **: 16:33:37.282: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(key-mapper-gtk:28879): Gtk-CRITICAL **: 16:33:37.282: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(key-mapper-gtk:28879): Gtk-CRITICAL **: 16:33:37.282: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)

**Comment by sezanzeb** [comment] 2021-01-30 15:43
what is "doas"?

Is the below output generated via "sudo key-mapper-gtk -d`?

**Comment by sezanzeb** [comment] 2021-01-30 15:46
Please try to run in a python3 shell:

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
Gtk.Window()
```

does that fail as well?

(https://forums.opensuse.org/showthread.php/538415-Possible-bug-in-libgtk-3-arandr-crashes-with-SEGFAULT)

**Comment by faultydev** [comment] 2021-01-30 18:05
> what is "doas"?
> 
> Is the output generated via `sudo key-mapper-gtk -d`?

the output was generated with sudo key-mapper-gtk -d yes.

doas is sudo. just way smaller.

the code you asked me to excute worked? it just executed. nothing else.

**Comment by sezanzeb** [comment] 2021-01-30 18:17
Great, thanks for checking.

Please try to install from this branch: https://github.com/sezanzeb/key-mapper/tree/no-css and see if that fixes anything

**Comment by faultydev** [comment] 2021-01-31 12:39
Alright, sorry for the late reply... I'm getting the same error.
I deleted the program from the AUR and checked out the no-css branch..

here is the `sudo key-mapper-gtk -d`:
```
0.14845 DEBUG: logger.py, line 181, Using rich.traceback
0.16042 INFO: logger.py, line 152, key-mapper 0.6.0
0.16084 INFO: logger.py, line 155, python-evdev 1.4.0
0.16091 WARNING: logger.py, line 161, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.16103 DEBUG: logger.py, line 167, pid 1755
0.18076 DEBUG: data.py, line 85, Found data at "/usr/share/key-mapper"

(key-mapper-gtk:1755): Gtk-CRITICAL **: 13:34:12.083: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(key-mapper-gtk:1755): Gtk-CRITICAL **: 13:34:12.083: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(key-mapper-gtk:1755): Gtk-CRITICAL **: 13:34:12.083: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
```

systemctl status:
```
key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2021-01-31 13:32:05 CET; 5min ago
   Main PID: 547 (key-mapper-serv)
      Tasks: 3 (limit: 9401)
     Memory: 47.7M
     CGroup: /system.slice/key-mapper.service
             └─547 /usr/bin/python3 /usr/bin/key-mapper-service

Jan 31 13:31:55 nullPC systemd[1]: Starting Service to inject keycodes without the GUI application...
Jan 31 13:32:05 nullPC key-mapper-service[547]: This output is also stored in "/root/.log/key-mapper"
Jan 31 13:32:05 nullPC key-mapper-service[547]: Logging to "/root/.log/key-mapper/log"
Jan 31 13:32:05 nullPC key-mapper-service[547]: key-mapper 0.6.0
Jan 31 13:32:05 nullPC key-mapper-service[547]: python-evdev 1.4.0
Jan 31 13:32:05 nullPC systemd[1]: Started Service to inject keycodes without the GUI application.
Jan 31 13:32:58 nullPC key-mapper-service[547]: Stopping all injections
```

**Comment by sezanzeb** [comment] 2021-01-31 14:15
unexpected.

Please try the new commit of the no-css branch again and log the output of `sudo key-mapper-gtk -d` again, it contains some more verbose logging for the window initialization.

**Comment by faultydev** [comment] 2021-02-01 14:09
-- logs : sudo key-mapper-gtk -d --
No protocol specified
Unable to init server: Could not connect: Connection refused
Loaded config from "/home/faulty/.config/key-mapper/config.json"
0.12824 DEBUG: logger.py, line 183, Using rich.traceback
0.14087 INFO: logger.py, line 154, key-mapper 0.6.0 455e531da68a3df9172736297413c9ee8310c721
0.14128 INFO: logger.py, line 157, python-evdev 1.4.0
0.14135 WARNING: logger.py, line 163, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.14146 DEBUG: logger.py, line 169, pid 13391
0.17909 DEBUG: daemon.py, line 91, Connected to the service
0.17926 DEBUG: window.py, line 143, Building interface
0.18182 DEBUG: data.py, line 85, Found data at "/usr/share/key-mapper"

(key-mapper-gtk:13391): Gtk-CRITICAL **: 15:06:52.903: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(key-mapper-gtk:13391): Gtk-CRITICAL **: 15:06:52.903: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(key-mapper-gtk:13391): Gtk-CRITICAL **: 15:06:52.904: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
-- end --

-- logs : systemctl status --
key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2021-01-31 13:32:05 CET; 1 day 1h ago
   Main PID: 547 (key-mapper-serv)
      Tasks: 3 (limit: 9401)
     Memory: 28.5M
     CGroup: /system.slice/key-mapper.service
             └─547 /usr/bin/python3 /usr/bin/key-mapper-service

Jan 31 13:31:55 nullPC systemd[1]: Starting Service to inject keycodes without the GUI application...
Jan 31 13:32:05 nullPC key-mapper-service[547]: This output is also stored in "/root/.log/key-mapper"
Jan 31 13:32:05 nullPC key-mapper-service[547]: Logging to "/root/.log/key-mapper/log"
Jan 31 13:32:05 nullPC key-mapper-service[547]: key-mapper 0.6.0
Jan 31 13:32:05 nullPC key-mapper-service[547]: python-evdev 1.4.0
Jan 31 13:32:05 nullPC systemd[1]: Started Service to inject keycodes without the GUI application.
Jan 31 13:32:58 nullPC key-mapper-service[547]: Stopping all injections
-- end --

**Comment by sezanzeb** [comment] 2021-02-01 14:29
Thanks

> This bug happens when trying to create a GTK widget without X server access
https://github.com/Nuitka/Nuitka/issues/607#issuecomment-608313934

Are you running X or Wayland? `echo $XDG_SESSION_TYPE`. It should work on both though

I'll check the proposed fix from there https://github.com/Nuitka/Nuitka/issues/607#issuecomment-650217096 later and insert it in the line before that one: https://github.com/sezanzeb/key-mapper/blob/main/bin/key-mapper-gtk#L51. Or you could also do that if you want, and if it fixes it feel free to create a pull request for that line.

I wasn't able to figure out if `Unable to init server: Could not connect: Connection refused` is X or DBus related, maybe there is a connection between those two errors.

**Comment by sezanzeb** [comment] 2021-02-02 23:19
I pushed that fix and added the style loading back in. Please let me know if it works as soon as you have time, no hurries

**Comment by faultydev** [comment] 2021-02-03 13:45
I'm on "x11"!

now it gave me this:
```
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(key-mapper-gtk:2645): Gtk-WARNING **: 14:42:35.403: cannot open display: :1
```

**Comment by sezanzeb** [comment] 2021-02-03 17:36
Looks like it fails right at the start on `Gtk.init()`. Sounds like a general issue on your arch installation, since nothing key-mapper specific happened at that point.

Please execute this again, but this time there is `Gtk.init()` inside and use `sudo python3` to open the console:

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
Gtk.init()
Gtk.Window()
```

**Comment by faultydev** [comment] 2021-02-03 17:39
-- Python 3 output --
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(test.py:6075): Gtk-WARNING **: 18:38:14.288: cannot open display: :1
-- end --

oh i never had this before so i thought it was on your side :o

**Comment by sezanzeb** [comment] 2021-02-03 17:43
is sudo symlinked as doas? `ls -l /bin/sudo`

**Comment by faultydev** [comment] 2021-02-03 17:44
looks like it
`lrwxrwxrwx 1 root root 13 Jan 29 19:05 /bin/sudo -> /usr/bin/doas`

**Comment by sezanzeb** [comment] 2021-02-03 17:47
it might be caused by doas then. You can verify that by installing sudo. And if that fails you could take the minimal example from above an open an issue in their bugtracker

**Comment by faultydev** [comment] 2021-02-03 17:59
Okay so I reinstalled the program from the AUR with the original sudo installed and it threw me this...

-- output --
```
0.53558 DEBUG: logger.py, line 181, Using rich.traceback
0.55002 INFO: logger.py, line 152, key-mapper 0.6.0
0.55044 INFO: logger.py, line 155, python-evdev 1.4.0
0.55051 WARNING: logger.py, line 161, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.55062 DEBUG: logger.py, line 167, pid 11199
0.58828 DEBUG: data.py, line 85, Found data at "/usr/share/key-mapper"
0.73633 DEBUG: getdevices.py, line 101, Discovering device paths
0.74596 SPAM: getdevices.py, line 139, Found "3,5215,525", "/dev/input/event9", "GXT 164 Gaming Mouse Consumer Control" 
0.74626 SPAM: getdevices.py, line 139, Found "3,5215,525", "/dev/input/event8", "GXT 164 Gaming Mouse" 
0.74638 SPAM: getdevices.py, line 139, Found "3,5215,525", "/dev/input/event7", "GXT 164 Gaming Mouse" 
0.74654 SPAM: getdevices.py, line 139, Found "25,0,0", "/dev/input/event13", "HP WMI hotkeys" 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/site-packages/key_mapper-0.6.0-py3.9.egg/keymapper/getdevices.py", line 122, in run
TypeError: object of type 'NoneType' has no len()

```

**Comment by sezanzeb** [comment] 2021-02-03 18:03
pushed a fix to main

**Comment by faultydev** [comment] 2021-02-03 18:09
it works!
thanks for helping me fix this issue!

**Comment by sezanzeb** [comment] 2021-02-03 18:10
you're welcome

**Closed by sezanzeb** 2021-02-03 18:10 UTC
