### ISSUE TITLE
Mappings not autoloaded

### ISSUE THREAD

**Issue by amadeusp** [sezanzeb/key-mapper#8] opened 2020-12-27 18:27 UTC
I love this app! Thanks for making it! <3

I am on Manjaro 20.2 GNOME running the 5.9.1-1-rt19-MANJARO kernel.

I use key-mapper-git 0.4.0-1 from the AUR.

My mappings only work after performing the following steps:
1. Launch key-mapper-gtk
2. Press "Save"
3. Press "Apply"

However, as soon as I close the GUI the mappings stop to work.

"Autoload" is activated but when rebooting the mappings do not work.

I ran `sudo usermod -a -G input $USER` already with no effect.

I also tried `sudo key-mapper-service --setup-permissions` but get: `error: unrecognized arguments: --setup-permissions` in return.

Many thanks for your help!

Best

Amadeus

**Comment by sezanzeb** [comment] 2020-12-27 18:32
Hi, thanks!

that means the service is not running. Please run `sudo systemctl start key-mapper` and try again.

`sudo key-mapper-service --setup-permissions` is outdated and I moved on to using proper pkexec and systemctl instead to grant injection and reading rights only to those processes that need it.

**Comment by sezanzeb** [comment] 2020-12-27 18:34
Also run `sudo systemctl enable key-mapper` for the autoloading to work. I thought the installation on manjaro automatically enables the service though, I need to check that again.

**Comment by amadeusp** [comment] 2020-12-27 18:52
Thanks a lot! `sudo systemctl enable key-mapper` did the trick!

**Comment by sezanzeb** [comment] 2020-12-27 19:02
I pushed changes to the AUR package to enable and start the service from now on

**Comment by amadeusp** [comment] 2020-12-31 15:28
Strangely, I still have to manually set up everything again after rebooting. The settings are still not saved permanently/not loaded automatically.

**Comment by sezanzeb** [comment] 2020-12-31 15:30
please post some log output when starting "sudo key-mapper-gtk -d", and when starting `key-mapper-gtk-pkexec`.

Try to save a preset, which generates some logs as well.

**Comment by amadeusp** [comment] 2020-12-31 23:13
I uninstalled the package and built it freshly via pacman and then ran some tests.

* * *
Computer started and just logged in.

Mappings not working.

* * *

Steps performed after executing sudo key-mapper-gtk:
1. Restore Defaults
2. Save
3. Apply
4. Close

Mappings worked after that and did continue to work after closing the GUI.

```
➜  ~ sudo key-mapper-gtk
Loaded config from "/home/username/.config/key-mapper/config.json"
Writing "/home/username/.config/key-mapper/xmodmap.json"
key-mapper 0.4.0
python-evdev 1.3.0
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Logitech BRIO", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Sleep Button"
Loading preset from "/home/username/.config/key-mapper/presets/USB-HID Keyboard/username.json"
Device "USB-HID Keyboard" is currently mapped
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Logitech BRIO", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Sleep Button"
Applied system default for "username"
Updating configs for "USB-HID Keyboard", "username"
Saving preset to /home/username/.config/key-mapper/presets/USB-HID Keyboard/username.json
Applying preset "username" for "USB-HID Keyboard"
Device "USB-HID Keyboard" is currently mapped

(key-mapper-gtk:3954): Gtk-CRITICAL **: 23:46:43.077: gtk_main_quit: assertion 'main_loops != NULL' failed
```

* * *

Steps performed after executing sudo key-mapper-gtk-pkexec:
1. Restore Defaults
2. Save
3. Apply
4. Close

Mappings did continue to work after closing the GUI.

```
➜  ~ sudo key-mapper-gtk-pkexec
Loaded config from "/home/username/.config/key-mapper/config.json"
Writing "/home/username/.config/key-mapper/xmodmap.json"
key-mapper 0.4.0
python-evdev 1.3.0
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Logitech BRIO", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Sleep Button"
Loading preset from "/home/username/.config/key-mapper/presets/USB-HID Keyboard/username.json"
Device "USB-HID Keyboard" is currently mapped
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Logitech BRIO", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Sleep Button"
Applied system default for "username"
Updating configs for "USB-HID Keyboard", "username"
Saving preset to /home/username/.config/key-mapper/presets/USB-HID Keyboard/username.json
Applying preset "username" for "USB-HID Keyboard"
Device "USB-HID Keyboard" is currently mapped

(key-mapper-gtk:4706): Gtk-CRITICAL **: 23:49:11.499: gtk_main_quit: assertion 'main_loops != NULL' failed
```

* * *

```
➜  ~ systemctl status key-mapper
● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-12-31 23:44:22 CET; 6min ago
   Main PID: 1249 (key-mapper-serv)
      Tasks: 4 (limit: 57738)
     Memory: 47.1M
     CGroup: /system.slice/key-mapper.service
             ├─1249 /usr/bin/python3 /usr/bin/key-mapper-service
             └─4723 /usr/bin/python3 /usr/bin/key-mapper-service

Dez 31 23:46:39 computer-name key-mapper-service[1249]: Loaded config from "/home/root/.config/key-mapper/config.json"
Dez 31 23:46:39 computer-name key-mapper-service[1249]: Loading preset from "/home/username/.config/key-mapper/presets/USB-HID Keyboa>
Dez 31 23:46:39 computer-name key-mapper-service[3978]: xset:  unable to open display ""
Dez 31 23:46:39 computer-name key-mapper-service[3977]: Starting injecting the mapping for "USB-HID Keyboard"
Dez 31 23:49:05 computer-name key-mapper-service[4717]: xset:  unable to open display ""
Dez 31 23:49:05 computer-name key-mapper-service[1249]: Stopping injecting keycodes for device "USB-HID Keyboard"
Dez 31 23:49:07 computer-name key-mapper-service[1249]: Loaded config from "/home/root/.config/key-mapper/config.json"
Dez 31 23:49:07 computer-name key-mapper-service[1249]: Loading preset from "/home/username/.config/key-mapper/presets/USB-HID Keyboa>
Dez 31 23:49:07 computer-name key-mapper-service[4724]: xset:  unable to open display ""
Dez 31 23:49:07 computer-name key-mapper-service[4723]: Starting injecting the mapping for "USB-HID Keyboard"
```

* * *

Restarted computer.

Mappings not working after logging in.

```
➜  ~ systemctl status key-mapper
● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendo>
     Active: active (running) since Thu 2020-12-31 23:56:02 CET; 27s ago
   Main PID: 1238 (key-mapper-serv)
      Tasks: 3 (limit: 57738)
     Memory: 42.3M
     CGroup: /system.slice/key-mapper.service
             └─1238 /usr/bin/python3 /usr/bin/key-mapper-service

Dez 31 23:56:02 computer-name systemd[1]: Starting Service to inject keycodes>
Dez 31 23:56:02 computer-name key-mapper-service[1238]: Loaded config from "/>
Dez 31 23:56:02 computer-name key-mapper-service[1353]: xmodmap:  unable to o>
Dez 31 23:56:02 computer-name key-mapper-service[1238]: This output is also s>
Dez 31 23:56:02 computer-name key-mapper-service[1238]: Logging to "/root/.lo>
Dez 31 23:56:02 computer-name key-mapper-service[1238]: key-mapper 0.4.0
Dez 31 23:56:02 computer-name key-mapper-service[1238]: python-evdev 1.3.0
Dez 31 23:56:02 computer-name systemd[1]: Started Service to inject keycodes >
```

* * *

I hope this helps.

**Comment by sezanzeb** [comment] 2021-01-01 01:54
ok thanks. I thought it might be because of resolving paths, which depends on key-mapper finding the current user properly in pkexec.

lets check if autoload is properly set: `cat ~/.config/key-mapper/config.json`

and try `key-mapper-control --command autoload` to see if the preset is loaded. Post the output of `systemctl status key-mapper` again (with a maximized terminal window)

**Comment by hixan** [comment] 2021-01-03 08:03
I am having the same issue and have found a bug in the code:
running `key-mapper-control --command autoload` gives the following error:
```
Loaded config from "/home/alexe/.config/key-mapper/config.json"
Writing "/home/alexe/.config/key-mapper/xmodmap.json"
Traceback (most recent call last):
  File "/usr/bin/key-mapper-control", line 148, in <module>
    main(options, daemon, xmodmap_path)
  File "/usr/bin/key-mapper-control", line 80, in main
    preset_path = get_preset_path(device, preset)
  File "/usr/lib/python3.9/site-packages/keymapper/paths.py", line 100, in get_preset_path
    assert not preset.endswith('.json')
AttributeError: 'dict' object has no attribute 'endswith'
```
I suspect that this is the cause of the issue.
Tracing the code I have found that the `config.json` produced by the program is not handled properly; the `"autoload"` key should have a `Dict[str, str]` but instead (in my case) has:
```
    "autoload": {
        "Megawin Technology Inc": {
            " Programmable Keyboard": "FINDME"
        },
        "AT Translated Set 2 keyboard": "FINDME"
    },
``` 
When loading, `config.iterate_autoload_presets()` returns the first key,value pair which is a string : dict causing the error.

It seems to be that the config supports manufacturer sub-categorization and the autoload function does not. I am happy to submit a PR to try fix this

**Comment by sezanzeb** [comment] 2021-01-03 11:48
you were both having the same issue, yes. Autoloading should work now

**Comment by sezanzeb** [comment] 2021-01-04 16:47
I'll take that heart emoji as a "yes it works". Also closing https://github.com/sezanzeb/key-mapper/pull/14

**Closed by sezanzeb** 2021-01-04 16:47 UTC

**Comment by amadeusp** [comment] 2021-01-05 07:24
Sorry, was super busy. Will confirm today as well. Thanks in advance!

**Comment by amadeusp** [comment] 2021-01-05 20:16
Here's my feedback:
1. Uninstalled key-mapper via pacman.
2. Deleted the key-mapper config file I made with the previous version of the app.
3. Rebooted the computer.
4. Installed key-mapper via pacman.
5. Launched key-mapper and setup my mappings, saved it as a preset, set it to autoload.
6. Mappings continued to work after closing the app.
7. Rebooted the computer.
8. Mappings did not work after logging in.
9. Launched key-mapper, mappings still did not work.
10. Clicked on Save, clicked on Apply, mappings worked again.
11. Closed the app, mappings continued to work.

* * *

```
➜  ~ sudo key-mapper-gtk  
Loaded config from "/home/userdir/.config/key-mapper/config.json"
Writing "/home/userdir/.config/key-mapper/xmodmap.json"
key-mapper 0.5.0
python-evdev 1.3.0
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Logitech BRIO", "Sleep Button"
Loading preset from "/home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json"
Device "USB-HID Keyboard" is currently mapped
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Logitech BRIO", "Sleep Button"
Updating configs for "USB-HID Keyboard", "amadeus"
Saving preset to /home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json
Applying preset "amadeus" for "USB-HID Keyboard"
Device "USB-HID Keyboard" is currently mapped
Applied system default for "amadeus"
Updating configs for "USB-HID Keyboard", "amadeus"
Saving preset to /home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json
ERROR: "mapping" is reserved and cannot be used as config key
Applying preset "amadeus" for "USB-HID Keyboard"
Device "USB-HID Keyboard" is currently mapped

(key-mapper-gtk:5405): Gtk-CRITICAL **: 21:01:52.882: gtk_main_quit: assertion 'main_loops != NULL' failed
```

I don't know what the ERROR means, as it is not represented in the UI (https://www.dropbox.com/s/2icytgvz8xmtf17/20210105-settings.png?dl=0).

* * *

```
➜  ~ key-mapper-gtk-pkexec
Loaded config from "/home/userdir/.config/key-mapper/config.json"
Writing "/home/userdir/.config/key-mapper/xmodmap.json"
key-mapper 0.5.0
python-evdev 1.3.0
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Logitech BRIO", "Sleep Button"
Loading preset from "/home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json"
Device "USB-HID Keyboard" is currently mapped
Found "key-mapper USB-HID Keyboard", "Apple Inc. Magic Trackpad 2", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Logitech BRIO", "Sleep Button"
Updating configs for "USB-HID Keyboard", "amadeus"
Saving preset to /home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json
Applying preset "amadeus" for "USB-HID Keyboard"
Device "USB-HID Keyboard" is currently mapped
Applied system default for "amadeus"
Updating configs for "USB-HID Keyboard", "amadeus"
Saving preset to /home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json
ERROR: "mapping" is reserved and cannot be used as config key
Applying preset "amadeus" for "USB-HID Keyboard"
Device "USB-HID Keyboard" is currently mapped

(key-mapper-gtk:6698): Gtk-CRITICAL **: 21:07:06.974: gtk_main_quit: assertion 'main_loops != NULL' failed
```

Same ERROR again.

* * *
➜  ~ systemctl status key-mapper
● key-mapper.service - Service to inject keycodes without the GUI application
     Loaded: loaded (/usr/lib/systemd/system/key-mapper.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-01-05 20:47:38 CET; 27min ago
   Main PID: 1282 (key-mapper-serv)
      Tasks: 4 (limit: 57738)
     Memory: 48.1M
     CGroup: /system.slice/key-mapper.service
             ├─1282 /usr/bin/python3 /usr/bin/key-mapper-service
             └─6760 /usr/bin/python3 /usr/bin/key-mapper-service

Jan 05 21:06:42 computer-name key-mapper-service[6720]: xset:  unable to open display ""
Jan 05 21:06:42 computer-name key-mapper-service[6719]: Starting injecting the mapping for "USB-HID Keyboard"
Jan 05 21:06:43 computer-name key-mapper-service[6719]: Left joystick as mouse, right joystick as wheel
Jan 05 21:06:43 computer-name key-mapper-service[6750]: xset:  unable to open display ""
Jan 05 21:06:43 computer-name key-mapper-service[1282]: Stopping injecting keycodes for device "USB-HID Keyboard"
Jan 05 21:06:45 computer-name key-mapper-service[1282]: Loaded config from "/home/userdir/.config/key-mapper/config.json"
Jan 05 21:06:45 computer-name key-mapper-service[1282]: Loading preset from "/home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json"
Jan 05 21:06:45 computer-name key-mapper-service[6761]: xset:  unable to open display ""
Jan 05 21:06:45 computer-name key-mapper-service[6760]: Starting injecting the mapping for "USB-HID Keyboard"
Jan 05 21:06:46 computer-name key-mapper-service[6760]: Left joystick as mouse, right joystick as wheel

**Comment by sezanzeb** [comment] 2021-01-05 20:47
`key-mapper-control --command autoload` please

**Comment by sezanzeb** [comment] 2021-01-06 00:21
As soon as I release the next improvements there will be a more verbose log on a failure to start an injection

**Comment by sezanzeb** [comment] 2021-01-06 13:56
I think I just fixed a problem in the autoload .desktop file for gnome.

Try installing from the AUR again

**Comment by amadeusp** [comment] 2021-01-07 21:45
First things first:
You fixed it! It works like a charm now! :) Thank you very much! <3

Here's what I did:
1. Uninstalled key-mapper.
2. Deleted the key-mapper config file.
3. Reinstalled key-mapper.
4. Launched key-mapper, setup my mappings, saved a preset, set it to autoload.
5. Config continued to work after quitting the key-mapper UI.
6. Logged out.
7. Logged in, config continued to work.

➜  ~ key-mapper-control --command autoload
Loaded config from "/home/userdir/.config/key-mapper/config.json"
Writing "/home/userdir/.config/key-mapper/xmodmap.json"
Loading preset from "/home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json"

**Comment by amadeusp** [comment] 2021-01-07 21:50
> I look forward to the result of autoloading using the cli.
> 
> sudo systemctl stop key-mapper
> sudo key-mapper-service -d
> in a different terminal:
> key-mapper-control --command autoload

```
➜  ~ sudo systemctl stop key-mapper
➜  ~ sudo key-mapper-service -d

Loaded config from "/home/userdir/.config/key-mapper/config.json"
Writing "/home/userdir/.config/key-mapper/xmodmap.json"
0.03087 INFO: logger.py, line 180, This output is also stored in "~/.log/key-mapper"
0.03106 INFO: logger.py, line 194, Logging to "/root/.log/key-mapper/log"
0.03677 INFO: logger.py, line 140, key-mapper 0.6.0
0.03703 INFO: logger.py, line 143, python-evdev 1.3.0
0.03707 WARNING: logger.py, line 149, Debug level will log all your keystrokes! Do not post this output in the internet if you typed in sensitive or private information with your device!
0.03713 DEBUG: logger.py, line 155, pid 8849
0.03899 DEBUG: daemon.py, line 133, Creating daemon
11.4684 INFO: daemon.py, line 219, Stopping all injections
11.4703 INFO: config.py, line 245, Loaded config from "/home/userdir/.config/key-mapper/config.json"
11.4726 DEBUG: getdevices.py, line 100, Discovering device paths
11.4747 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 05ac, product 0265, version 0110", "/dev/input/event11", "Apple Inc. Magic Trackpad 2"
11.4749 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 2341, product 8036, version 0101", "/dev/input/event21", "Arduino LLC Arduino Leonardo"
11.4750 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 046d, product 085e, version 0111", "/dev/input/event20", "Logitech BRIO Consumer Control"
11.4751 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 046d, product 085e, version 0317", "/dev/input/event19", "Logitech BRIO"
11.4752 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 046d, product c08a, version 0111", "/dev/input/event18", "Logitech MX Vertical Advanced Ergonomic Mouse System Control"
11.4754 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 046d, product c08a, version 0111", "/dev/input/event17", "Logitech MX Vertical Advanced Ergonomic Mouse Consumer Control"
11.4756 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 046d, product c08a, version 0111", "/dev/input/event16", "Logitech MX Vertical Advanced Ergonomic Mouse Keyboard"
11.4757 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 046d, product c08a, version 0111", "/dev/input/event15", "Logitech MX Vertical Advanced Ergonomic Mouse"
11.4759 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04d9, product 0192, version 0111", "/dev/input/event14", "USB-HID Keyboard"
11.4760 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04d9, product 0192, version 0111", "/dev/input/event13", "USB-HID Keyboard Consumer Control"
11.4761 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04d9, product 0192, version 0111", "/dev/input/event12", "USB-HID Keyboard System Control"
11.4762 SPAM: getdevices.py, line 126, Found "bus: 0003, vendor 04d9, product 0192, version 0111", "/dev/input/event10", "USB-HID Keyboard"
11.4764 SPAM: getdevices.py, line 126, Found "bus: 0019, vendor 0000, product 0003, version 0000", "/dev/input/event1", "Sleep Button"
11.4769 INFO: getdevices.py, line 189, Found "Apple Inc. Magic Trackpad 2", "Arduino LLC Arduino Leonardo", "Logitech BRIO Consumer Control", "Logitech BRIO", "Logitech MX Vertical Advanced Ergonomic Mouse", "USB-HID Keyboard", "Sleep Button"
11.4771 INFO: mapping.py, line 162, Loading preset from "/home/userdir/.config/key-mapper/presets/USB-HID Keyboard/amadeus.json"
11.4774 SPAM: mapping.py, line 195, Key((1, 65, 1),) maps to key_previous
11.4776 SPAM: mapping.py, line 195, Key((1, 66, 1),) maps to key_playpause
11.4777 SPAM: mapping.py, line 195, Key((1, 67, 1),) maps to key_forward
11.4778 SPAM: mapping.py, line 195, Key((1, 68, 1),) maps to key_mute
11.4779 SPAM: mapping.py, line 195, Key((1, 87, 1),) maps to key_volumedown
11.4781 SPAM: mapping.py, line 195, Key((1, 88, 1),) maps to key_volumeup
11.4782 SPAM: mapping.py, line 195, Key((1, 126, 1),) maps to super_l
11.4787 DEBUG: daemon.py, line 196, Using keycodes from "/home/userdir/.config/key-mapper/xmodmap.json"
11.4942 INFO: pid 8880, injector.py, line 377, Starting injecting the mapping for "USB-HID Keyboard"
11.4951 DEBUG: pid 8880, injector.py, line 258, Grab /dev/input/event14
11.4952 DEBUG: pid 8880, injector.py, line 392, Parsing macros for /dev/input/event14
11.4953 DEBUG: pid 8880, injector.py, line 404, No macros configured
11.5984 SPAM: pid 8880, injector.py, line 415, Injected capabilities for "/dev/input/event14": {('EV_SYN', 0): [('SYN_REPORT', 0), ('SYN_CONFIG', 1), ('?', 4), ('?', 21)], ('EV_KEY', 1): [('KEY_ESC', 1), ('KEY_1', 2), ('KEY_2', 3), ('KEY_3', 4), ('KEY_4', 5), ('KEY_5', 6), ('KEY_6', 7), ('KEY_7', 8), ('KEY_8', 9), ('KEY_9', 10), ('KEY_0', 11), ('KEY_MINUS', 12), ('KEY_EQUAL', 13), ('KEY_BACKSPACE', 14), ('KEY_TAB', 15), ('KEY_Q', 16), ('KEY_W', 17), ('KEY_E', 18), ('KEY_R', 19), ('KEY_T', 20), ('KEY_Y', 21), ('KEY_U', 22), ('KEY_I', 23), ('KEY_O', 24), ('KEY_P', 25), ('KEY_LEFTBRACE', 26), ('KEY_RIGHTBRACE', 27), ('KEY_ENTER', 28), ('KEY_LEFTCTRL', 29), ('KEY_A', 30), ('KEY_S', 31), ('KEY_D', 32), ('KEY_F', 33), ('KEY_G', 34), ('KEY_H', 35), ('KEY_J', 36), ('KEY_K', 37), ('KEY_L', 38), ('KEY_SEMICOLON', 39), ('KEY_APOSTROPHE', 40), ('KEY_GRAVE', 41), ('KEY_LEFTSHIFT', 42), ('KEY_BACKSLASH', 43), ('KEY_Z', 44), ('KEY_X', 45), ('KEY_C', 46), ('KEY_V', 47), ('KEY_B', 48), ('KEY_N', 49), ('KEY_M', 50), ('KEY_COMMA', 51), ('KEY_DOT', 52), ('KEY_SLASH', 53), ('KEY_RIGHTSHIFT', 54), ('KEY_KPASTERISK', 55), ('KEY_LEFTALT', 56), ('KEY_SPACE', 57), ('KEY_CAPSLOCK', 58), ('KEY_F1', 59), ('KEY_F2', 60), ('KEY_F3', 61), ('KEY_F4', 62), ('KEY_F5', 63), ('KEY_F6', 64), ('KEY_F7', 65), ('KEY_F8', 66), ('KEY_F9', 67), ('KEY_F10', 68), ('KEY_NUMLOCK', 69), ('KEY_SCROLLLOCK', 70), ('KEY_KP7', 71), ('KEY_KP8', 72), ('KEY_KP9', 73), ('KEY_KPMINUS', 74), ('KEY_KP4', 75), ('KEY_KP5', 76), ('KEY_KP6', 77), ('KEY_KPPLUS', 78), ('KEY_KP1', 79), ('KEY_KP2', 80), ('KEY_KP3', 81), ('KEY_KP0', 82), ('KEY_KPDOT', 83), ('KEY_ZENKAKUHANKAKU', 85), ('KEY_102ND', 86), ('KEY_F11', 87), ('KEY_F12', 88), ('KEY_RO', 89), ('KEY_KATAKANA', 90), ('KEY_HIRAGANA', 91), ('KEY_HENKAN', 92), ('KEY_KATAKANAHIRAGANA', 93), ('KEY_MUHENKAN', 94), ('KEY_KPJPCOMMA', 95), ('KEY_KPENTER', 96), ('KEY_RIGHTCTRL', 97), ('KEY_KPSLASH', 98), ('KEY_SYSRQ', 99), ('KEY_RIGHTALT', 100), ('KEY_HOME', 102), ('KEY_UP', 103), ('KEY_PAGEUP', 104), ('KEY_LEFT', 105), ('KEY_RIGHT', 106), ('KEY_END', 107), ('KEY_DOWN', 108), ('KEY_PAGEDOWN', 109), ('KEY_INSERT', 110), ('KEY_DELETE', 111), (['KEY_MIN_INTERESTING', 'KEY_MUTE'], 113), ('KEY_VOLUMEDOWN', 114), ('KEY_VOLUMEUP', 115), ('KEY_POWER', 116), ('KEY_KPEQUAL', 117), ('KEY_PAUSE', 119), ('KEY_KPCOMMA', 121), (['KEY_HANGEUL', 'KEY_HANGUEL'], 122), ('KEY_HANJA', 123), ('KEY_YEN', 124), ('KEY_LEFTMETA', 125), ('KEY_RIGHTMETA', 126), ('KEY_COMPOSE', 127), ('KEY_STOP', 128), ('KEY_AGAIN', 129), ('KEY_PROPS', 130), ('KEY_UNDO', 131), ('KEY_FRONT', 132), ('KEY_COPY', 133), ('KEY_OPEN', 134), ('KEY_PASTE', 135), ('KEY_FIND', 136), ('KEY_CUT', 137), ('KEY_HELP', 138), ('KEY_FORWARD', 159), ('KEY_PLAYPAUSE', 164), ('KEY_KPLEFTPAREN', 179), ('KEY_KPRIGHTPAREN', 180), ('KEY_F13', 183), ('KEY_F14', 184), ('KEY_F15', 185), ('KEY_F16', 186), ('KEY_F17', 187), ('KEY_F18', 188), ('KEY_F19', 189), ('KEY_F20', 190), ('KEY_F21', 191), ('KEY_F22', 192), ('KEY_F23', 193), ('KEY_F24', 194), ('KEY_UNKNOWN', 240), ('KEY_PREVIOUS', 412)], ('EV_MSC', 4): [('MSC_SCAN', 4)]}
11.5990 DEBUG: pid 8880, injector.py, line 247, No need to grab /dev/input/event13
11.6169 DEBUG: pid 8880, injector.py, line 247, No need to grab /dev/input/event12
11.6469 DEBUG: pid 8880, injector.py, line 258, Grab /dev/input/event10
11.6471 DEBUG: pid 8880, injector.py, line 392, Parsing macros for /dev/input/event10
11.6472 DEBUG: pid 8880, injector.py, line 404, No macros configured
11.7494 SPAM: pid 8880, injector.py, line 415, Injected capabilities for "/dev/input/event10": {('EV_SYN', 0): [('SYN_REPORT', 0), ('SYN_CONFIG', 1), ('?', 4), ('?', 17), ('?', 21)], ('EV_KEY', 1): [('KEY_ESC', 1), ('KEY_1', 2), ('KEY_2', 3), ('KEY_3', 4), ('KEY_4', 5), ('KEY_5', 6), ('KEY_6', 7), ('KEY_7', 8), ('KEY_8', 9), ('KEY_9', 10), ('KEY_0', 11), ('KEY_MINUS', 12), ('KEY_EQUAL', 13), ('KEY_BACKSPACE', 14), ('KEY_TAB', 15), ('KEY_Q', 16), ('KEY_W', 17), ('KEY_E', 18), ('KEY_R', 19), ('KEY_T', 20), ('KEY_Y', 21), ('KEY_U', 22), ('KEY_I', 23), ('KEY_O', 24), ('KEY_P', 25), ('KEY_LEFTBRACE', 26), ('KEY_RIGHTBRACE', 27), ('KEY_ENTER', 28), ('KEY_LEFTCTRL', 29), ('KEY_A', 30), ('KEY_S', 31), ('KEY_D', 32), ('KEY_F', 33), ('KEY_G', 34), ('KEY_H', 35), ('KEY_J', 36), ('KEY_K', 37), ('KEY_L', 38), ('KEY_SEMICOLON', 39), ('KEY_APOSTROPHE', 40), ('KEY_GRAVE', 41), ('KEY_LEFTSHIFT', 42), ('KEY_BACKSLASH', 43), ('KEY_Z', 44), ('KEY_X', 45), ('KEY_C', 46), ('KEY_V', 47), ('KEY_B', 48), ('KEY_N', 49), ('KEY_M', 50), ('KEY_COMMA', 51), ('KEY_DOT', 52), ('KEY_SLASH', 53), ('KEY_RIGHTSHIFT', 54), ('KEY_KPASTERISK', 55), ('KEY_LEFTALT', 56), ('KEY_SPACE', 57), ('KEY_CAPSLOCK', 58), ('KEY_F1', 59), ('KEY_F2', 60), ('KEY_F3', 61), ('KEY_F4', 62), ('KEY_F5', 63), ('KEY_F6', 64), ('KEY_F7', 65), ('KEY_F8', 66), ('KEY_F9', 67), ('KEY_F10', 68), ('KEY_NUMLOCK', 69), ('KEY_SCROLLLOCK', 70), ('KEY_KP7', 71), ('KEY_KP8', 72), ('KEY_KP9', 73), ('KEY_KPMINUS', 74), ('KEY_KP4', 75), ('KEY_KP5', 76), ('KEY_KP6', 77), ('KEY_KPPLUS', 78), ('KEY_KP1', 79), ('KEY_KP2', 80), ('KEY_KP3', 81), ('KEY_KP0', 82), ('KEY_KPDOT', 83), ('KEY_ZENKAKUHANKAKU', 85), ('KEY_102ND', 86), ('KEY_F11', 87), ('KEY_F12', 88), ('KEY_RO', 89), ('KEY_KATAKANA', 90), ('KEY_HIRAGANA', 91), ('KEY_HENKAN', 92), ('KEY_KATAKANAHIRAGANA', 93), ('KEY_MUHENKAN', 94), ('KEY_KPJPCOMMA', 95), ('KEY_KPENTER', 96), ('KEY_RIGHTCTRL', 97), ('KEY_KPSLASH', 98), ('KEY_SYSRQ', 99), ('KEY_RIGHTALT', 100), ('KEY_HOME', 102), ('KEY_UP', 103), ('KEY_PAGEUP', 104), ('KEY_LEFT', 105), ('KEY_RIGHT', 106), ('KEY_END', 107), ('KEY_DOWN', 108), ('KEY_PAGEDOWN', 109), ('KEY_INSERT', 110), ('KEY_DELETE', 111), (['KEY_MIN_INTERESTING', 'KEY_MUTE'], 113), ('KEY_VOLUMEDOWN', 114), ('KEY_VOLUMEUP', 115), ('KEY_POWER', 116), ('KEY_KPEQUAL', 117), ('KEY_PAUSE', 119), ('KEY_KPCOMMA', 121), (['KEY_HANGEUL', 'KEY_HANGUEL'], 122), ('KEY_HANJA', 123), ('KEY_YEN', 124), ('KEY_LEFTMETA', 125), ('KEY_RIGHTMETA', 126), ('KEY_COMPOSE', 127), ('KEY_STOP', 128), ('KEY_AGAIN', 129), ('KEY_PROPS', 130), ('KEY_UNDO', 131), ('KEY_FRONT', 132), ('KEY_COPY', 133), ('KEY_OPEN', 134), ('KEY_PASTE', 135), ('KEY_FIND', 136), ('KEY_CUT', 137), ('KEY_HELP', 138), ('KEY_FORWARD', 159), ('KEY_PLAYPAUSE', 164), ('KEY_F13', 183), ('KEY_F14', 184), ('KEY_F15', 185), ('KEY_F16', 186), ('KEY_F17', 187), ('KEY_F18', 188), ('KEY_F19', 189), ('KEY_F20', 190), ('KEY_F21', 191), ('KEY_F22', 192), ('KEY_F23', 193), ('KEY_F24', 194), ('KEY_UNKNOWN', 240), ('KEY_PREVIOUS', 412)], ('EV_MSC', 4): [('MSC_SCAN', 4)], ('EV_LED', 17): [('LED_NUML', 0), ('LED_CAPSL', 1), ('LED_SCROLLL', 2)]}
11.8228 DEBUG: pid 8880, injector.py, line 495, Started consumer to inject to /dev/input/event14, fd 43
11.8233 DEBUG: pid 8880, injector.py, line 495, Started consumer to inject to /dev/input/event10, fd 46
```

**Comment by sezanzeb** [comment] 2021-01-08 00:26
actually, I'm pretty sure it was already expected to keep injecting after a logout and login. You need to disable the injection before that in order to test if it works

**Comment by amadeusp** [comment] 2021-01-08 16:09
From the perspective of auto loading the mappings everything seems to be fine now. They work without further ado after reboots as well.

**Comment by sezanzeb** [comment] 2021-01-08 16:16
great, thanks for letting me know
